name: Telegram Clock

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kutubxonalarni o'rnatish
        run: pip install -r requirements.txt

      - name: Telegram Clock ishga tushirish
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE: ${{ secrets.PHONE }}
        run: python main.py
